### ISSUE TITLE
Spanish translation and maintainer

### ISSUE THREAD

**Issue by ceoaliongroo** [jlevy/the-art-of-command-line#121]

**Comment by jlevy** [comment]
That's great! Are you willing to maintain (and/or review PRs on) the Spanish one to keep it current?

**Comment by ceoaliongroo** [comment]
Yes, i can

**Comment by jlevy** [comment]
Thanks again for #122 -- first version is in.

Note that the English has a few additions since your translation. You can track/add them by comparing with your rep and then creating new PRs for updates to the -es file. For example:
https://github.com/ceoaliongroo/the-art-of-command-line/compare/master...jlevy:master#diff-04c6e90faac2675aa89e2176d2eec7d8

Thanks again!

**Comment by ceoaliongroo** [comment]
sure!

**Comment by aaossa** [comment]
Can I make a PR trying to fix the spanish translation? I speak spanish and it was hard to read. Thanks.

**Comment by BishopWolf** [comment]
I created a small PR with revision for grammar and ortography.

**Comment by ceoaliongroo** [comment]
@aaossa, You can add your comments in the @BishopWolf  PR #164 

Thanks

**Comment by jlevy** [comment]
Thanks to @ceoaliongroo initial translation and agreement to maintain and improvements from @BishopWolf I'm marking this as closed -- but @aaossa and all others, please continue to file new issues/PRs for improvements.
