### ISSUE TITLE
Is LC_ALL=C really sound advice?

### ISSUE THREAD

**Issue by voltagex** [jlevy/the-art-of-command-line#22]
See discussion at https://news.ycombinator.com/item?id=9722587

**Comment by jlevy** [comment]
For the record, the discussion there tended to focus on either one or the other of two different facts:

- You absolutely need to be aware of and manage language and locale settings diligently. This is a big topic, but generally, whenever possible, use UTF8. And you generally don't want to change your desktop OS or applications' locale or language settings other than that.

- However, if you are processing data files and are aware of the implications, and can get away with treating data as binary instead of character streams -- for example, any of the command sequences that use sort/uniq for uniqueness or set union/intersection/difference -- then using C locale is *way* faster. As in, the difference between doing something in an hour on a big machine and rewriting a whole pipeline in Hadoop. A good fact to know.

However, it's obvious I didn't make the simultaneous truth of both these points clear. I'll rewrite.

**Comment by jleclanche** [comment]
@jlevy LC_ALL encompasses collation, i18n and encoding. Encoding is the biggest issue and it's unlikely to be causing performance issues. Have you tried `LC_COLLATE=C` instead?

**Comment by jlevy** [comment]
I've not tested lots of variations there, and it's been a few years since I ran a benchmark. My overall point is just that if you care a lot about performance for data pipelines and the like, and are OK treating data as binary, disable them all -- there's no benefit. This only applies to the narrow case of some kinds of operations, however -- not general advice to ignore encodings and collation!

**Comment by jlevy** [comment]
Do let me know if you still think the (rewritten) point in the doc is unclear.

**Comment by jleclanche** [comment]
The rewritten version is a lot better, yeah. This probably warrants benchmarking and a more in-depth look into, but I wanted to avoid any notion of encoding or localization having a meaningful impact on performance.

Anyway my primary concern was with the recommendation of putting it in a rc file. It will eventually break and when it does, you won't know why, and it'll result in super weird heisenbugs such as "My prompt behaves differently when my working directory is a git repository with at least two items in the stash". :)

**Comment by jlevy** [comment]
Sure. As with so many things, though, "it depends." If for example, you're dealing with scripts running over large, extremely multilingual UTF8 files (think of working on a search engine, for example), it's often better if you just always ensure your shell is in C locale. It'll not be the standard English or French or Norwegian sort order, but there is no well-defined multilingual collation order anyway, nor do you need to waste times parse the files as UTF8, or worrying about behavior on invalid UTF8 encodings.

Also, if you look at the code in many i18n routines, it's very apparent why they're so much slower, given the complexity. Some Unicode transformations are disturbingly slow, if you're at data sizes where it matters.

Upshot: Sometimes you treat data as binary, sometimes you treat it as characters.
