### ISSUE TITLE
es: Verify the meaning of the source and check translation

### ISSUE THREAD

**Issue by ceoaliongroo** [jlevy/the-art-of-command-line#226]
185: tales como la realización de operaciones u operaciones singulares debajo... is this ok?
236: un resumen del montículo "heap summary" => un resumen del montón.
256: la estadística histórica en => estadística sobre.

**Comment by aaossa** [comment]
Could you add the original english context and the spanish suggested one? Maybe @mayra-cabrera could help to translate this too.

**Comment by mayra-cabrera** [comment]
### 185: tales como la realización de operaciones u operaciones singulares debajo
> Know that locale affects a lot of command line tools in subtle ways, including sorting order (collation) and performance. Most Linux installations will set LANG or other locale variables to a local setting like US English. But be aware sorting will change if you change locale. And know i18n routines can make sort or other commands run many times slower. In some situations (such as the set operations or uniqueness operations below) you can safely ignore slow i18n routines entirely and use traditional byte-based sort order, using export LC_ALL=C.

According to the former, I think "set operations or uniqueness operations below" refers to the definitions in the following lines, so a proper translation could be:

*En algunas situaciones, como el conjunto de operaciones o las operaciones singulares descritas abajo, puedes ignorar completamente las rutas i18n lentas, y usar en su lugar el sort tradicional basado en bytes, a través de LC_ALL=C*

If is not referring to the definition or examples, it could be changed to:

*En algunas situaciones, como el conjunto de operaciones u operaciones singulares, puedes ignorar completamente las rutas i18n lentas, y usar en su lugar el sort tradicional basado en bytes, a través de LC_ALL=C*

### 236: un resumen del montículo "heap summary" => un resumen del montón.

> Java system debugging is a different kettle of fish, but a simple trick on Oracle's and some other JVMs is that you can run kill -3 <pid> and a full stack trace and heap summary (including generational garbage collection details, which can be highly informative) will be dumped to stderr/logs. The JDK's jps, jstat, jstack, jmap are useful. SJK tools are more advanced.

This one is hard to translate to Spanish since is using a lot of technical concepts that doesn't a have a direct translation. 

*El sistema de depuración de Java es un tema diferente, pero un simple truco para Oracle y para otras JVM's es que puedes ejecutar `kill -3 <pid>` y una descripción completa en conjunto con un resumen, que incluye detalles del recolector de basura que pueden ser altamente informativos, serán descargados en los stderr/logs.  Las herramientas jps, jstat, jstack y jmap del JDK son útiles. Mientras que las herramientas SJK más avanzadas.*

I'm not completely satisfied about this one, maybe is a good idea to keep technical concepts in his original version like:

*El sistema de depuración de Java es un tema diferente, pero un simple truco para Oracle y para otras JVM's es que puedes ejecutar `kill -3 <pid>` y un "full stack trace" junto con un "heap summary", que que incluye detalles del recolector de basura que pueden ser altamente informativos, serán descargados en los stderr/logs.  Las herramientas jps, jstat, jstack y jmap del JDK son útiles. Mientras que las herramientas SJK más avanzadas.*

### 256: la estadística histórica en => estadística sobre.

> When debugging why something went wrong in the past, sar can be very helpful. It shows historic statistics on CPU, memory, network, etc.

In that context "Estadística sobre" or "Estadística acerca" are more suitable than "estadística histórica en", so

*Cuando depuras porque algo salió mal, `sar` puede ser muy útil. Muestra estadísticas sobre el CPU, memoria, red, etc.*

@aaossa @ceoaliongroo what do you think?

**Comment by aaossa** [comment]
I like it, but we need to choose yet between ´tú´ y ´usted´. Once we close this issue we could send a new PR.

**Comment by jlevy** [comment]
@ceoaliongroo Can this be closed?

**Comment by ceoaliongroo** [comment]
yes, could be close. 

thanks
