### ISSUE TITLE
ar: Trouble with arabic fork

### ISSUE THREAD

**Issue by elacheche** [jlevy/the-art-of-command-line#342]
Hey @jlevy & @* !

So, Maybe am the only new git user here, maybe not x(

I had issues keeping my Fork Synced to the master and my local repo synced to my fork without conflicts.

I'm looking for help to achieve that.. Based on the "guidelines for contributing" I should ask other people to fork my repo and work on my languages translation.. Then once the language file is fully translated I should create a PR  to the master..

This way my fork will have commits ahead the master, and commits behind the master.. It's a good thing to help translators bypassing the git conflict that may happen when forking and working on the project.

As I said, I'm a git n00b.. x(

PS: I tried to fix that myself, but my fork is missed up now.. So I think that I should delete my  fork and fork the project again.

**Comment by elacheche** [comment]
Anyone? x)

**Comment by adrienbrunet** [comment]
Hi, 

I'm not a contributor to this repo but you can have a look at `git rebase` before merging. Simply said, it pulls commits from master and tries to replay your changes so that you only have commits ahead of master. But maybe then, the translations will be a bit outdated.

Hope this helps. I still feel I havn't really answered your questions :sob:

**Comment by jlevy** [comment]
@elacheche It looks like you had a conflict because you also modified the language header, which changed on the main repository, and also, that the conflict was committed. https://github.com/elacheche/the-art-of-command-line

Perhaps the simplest thing would be for you to make a backup of your README-ar.md file (don't lose it! it should contain all the good work), delete the repository, and re-fork again, and re-commit. Sort of a pain but it's hard to undo commits that are erroneous. Either that, or you'll need to learn how to "git reset --hard" and re-commit the good file.

Going forward, if you only touch README-ar.md you'll avoid conflicts. Hope that helps! Possibly someone here can walk you through further Git tips.

**Comment by jlevy** [comment]
@elacheche Take a look at #343. Hope you guys can join forces somehow. If your fork has issues, perhaps re-fork the translation in progress there, or help review that PR? Thanks!

**Comment by elacheche** [comment]
It was a busy week @jlevy  :( Sorry I couldn't achieve what I promised.. I'll remove my existant fork an re-fork the other one :) And try to help them :)

**Comment by jlevy** [comment]
Cool. :) Thanks @elacheche .
